import { useState } from "react";
import { RefreshCw } from "lucide-react";
import { dateLabel, outcomes, OutcomeBadge, prospect } from "./LeadViews";

// The page owns the existing Supabase client and all fetching; no second subscription.
export default function LeadsPanel({ leads = [], loading, onRefresh }) {
  const [filter, setFilter] = useState("all");
  const filtered = filter === "all" ? leads : leads.filter(lead => lead.outcome === filter);
  return <section className="rounded-[28px] border border-white bg-white/80 p-4 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-1">{["all", "booked", "callback", "not_interested", "do_not_call"].map(value => <button key={value} onClick={() => setFilter(value)} aria-pressed={filter === value} className={`min-h-11 rounded-full px-3 text-xs transition ${filter === value ? "bg-slate-900 text-white" : "text-slate-600 hover:bg-slate-100"}`}>{value === "all" ? "All" : outcomes[value].label}</button>)}</div><button onClick={onRefresh} disabled={loading} aria-label="Refresh leads" className="flex h-11 w-11 items-center justify-center rounded-full border border-slate-200 hover:bg-slate-50"><RefreshCw size={16} className={loading ? "animate-spin" : ""} /></button></div>
    <div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-slate-200 text-[11px] text-slate-500"><tr><th className="py-4 pr-4 font-normal">Prospect / Business</th><th className="hidden px-3 font-normal md:table-cell">Phone</th><th className="px-2 font-normal">Outcome</th><th className="hidden px-3 font-normal lg:table-cell">Follow-up</th><th className="hidden pl-3 font-normal sm:table-cell">Updated</th></tr></thead><tbody>{filtered.map(lead => <tr key={lead.id} className="border-b border-slate-100 last:border-0"><td className="max-w-[160px] break-words py-5 pr-3"><p className="font-medium">{prospect(lead)}</p><p className="mt-1 text-xs text-slate-500 md:hidden">{lead.phone_number || "—"}</p>{lead.followup_time && <p className="mt-1 text-xs text-amber-800 lg:hidden">{dateLabel(lead.followup_time)}</p>}</td><td className="hidden px-3 text-slate-500 md:table-cell">{lead.phone_number || "—"}</td><td className="px-2"><OutcomeBadge outcome={lead.outcome} /></td><td className="hidden px-3 text-xs text-slate-500 lg:table-cell">{dateLabel(lead.followup_time)}</td><td className="hidden pl-3 text-xs text-slate-500 sm:table-cell">{dateLabel(lead.updated_at || lead.created_at)}</td></tr>)}</tbody></table></div>{!filtered.length && <p className="py-14 text-center text-sm text-slate-500">{loading ? "Loading leads…" : "No leads yet"}</p>}
  </section>;
}
