import { ArrowUpRight, AudioWaveform } from "lucide-react";
import { dateLabel, outcomes, OutcomeBadge, prospect } from "./LeadViews";
import { durationLabel, StatePill } from "./VoiceAgent";
const card = "rounded-[28px] border border-white/80 bg-white/75 p-6 shadow-[0_3px_18px_rgba(54,62,87,0.025)] transition duration-200 hover:-translate-y-0.5";
export default function Overview({ leads, available, voiceState, seconds, startedAt, onVoice }) {
  const counts = Object.fromEntries(Object.keys(outcomes).map(key => [key, leads.filter(lead => lead.outcome === key).length]));
  const completed = leads.filter(lead => lead.outcome && lead.outcome !== "in_progress" && outcomes[lead.outcome]).length;
  const rate = value => available && completed ? `${Math.round(value / completed * 100)}%` : "—";
  const followups = leads.filter(lead => ["callback", "booked"].includes(lead.outcome)).slice(0, 3);
  const days = Array.from({ length: 7 }, (_, i) => { const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - 6 + i); return date; });
  const activity = days.map(day => leads.filter(lead => { const date = new Date(lead.created_at); return date.toDateString() === day.toDateString(); }).length);
  const max = Math.max(...activity, 1);
  const metric = value => available ? value : "—";
  return <>
    <div className="mb-8 flex flex-col justify-between gap-7 lg:flex-row lg:items-end"><div><p className="mb-3 text-[11px] uppercase tracking-[0.2em] text-slate-500">Your workspace</p><h1 className="text-4xl tracking-tight sm:text-5xl">Overview</h1><p className="mt-3 text-sm text-slate-500">Voice operations at a glance.</p></div><div className="grid grid-cols-3 gap-6 sm:gap-12">{[[metric(leads.filter(lead => lead.call_sid).length), "Saved sessions"], [metric(counts.booked), "Booked"], [metric(leads.length), "Leads"]].map(([value, label]) => <div key={label}><p className="text-[38px] leading-none tracking-tight sm:text-[52px]">{value}</p><p className="mt-3 text-[11px] text-slate-500">{label}</p></div>)}</div></div>
    <div className="grid grid-cols-1 gap-4 lg:grid-cols-12 lg:gap-5">
      <section className="relative flex min-h-[330px] flex-col overflow-hidden rounded-[28px] bg-gradient-to-br from-[#cec8fb] via-[#dddafa] to-[#a5e3e7] p-6 lg:col-span-3 lg:row-span-2"><div className="flex items-center justify-between"><span className="text-[11px] uppercase tracking-widest text-slate-600">Elite AI</span><AudioWaveform size={20} /></div><div aria-hidden="true" className="relative mx-auto my-auto flex h-48 w-48 items-center justify-center rounded-full border border-white/40 bg-gradient-to-br from-white/60 via-[#afa2f3]/40 to-cyan-100 shadow-[inset_0_0_35px_rgba(255,255,255,0.7),0_20px_50px_rgba(109,92,231,0.12)]"><div className="absolute inset-5 rounded-full border border-white/60"/><AudioWaveform strokeWidth={1} className="h-24 w-24 text-white drop-shadow-sm" /></div><div className="mt-4"><h2 className="text-4xl tracking-tight">Maya</h2><p className="mb-5 mt-2 text-sm text-slate-600">Elite AI Voice Agent</p><div className="flex items-center justify-between"><StatePill state={voiceState} /><button onClick={onVoice} aria-label="Open voice session" className="flex h-11 w-11 items-center justify-center rounded-full bg-white/70 transition hover:bg-white"><ArrowUpRight size={20} /></button></div></div></section>
      <section className={`${card} lg:col-span-5`}><div className="flex items-start justify-between"><h2 className="text-base">Session activity</h2><span className="text-[11px] text-slate-500">Last 7 days</span></div><div className="mt-5 flex items-baseline gap-2"><span className="text-4xl tracking-tight">{metric(activity.reduce((a,b) => a+b, 0))}</span><span className="text-xs text-slate-500">saved sessions</span></div><div className="mt-5 flex h-24 items-end justify-between gap-3" aria-label="Daily session counts">{days.map((day, index) => <div key={day.toISOString()} className="flex h-full flex-1 flex-col items-center justify-end gap-2"><div className="flex w-full flex-1 items-end justify-center"><div title={`${day.toDateString()}: ${available ? activity[index] : "unavailable"}`} className={`w-full max-w-8 rounded-t-lg ${index === 6 ? "bg-[#8B7CFF]" : "bg-[#e5e1f7]"}`} style={{ height: available ? `${activity[index] / max * 100}%` : 0 }} /></div><span className="text-[10px] text-slate-500">{day.toLocaleDateString([], { weekday: "short" })}</span></div>)}</div></section>
      <section className={`${card} lg:col-span-4 lg:row-span-2`}><h2 className="text-base">Outcome distribution</h2><p className="mt-2 text-xs text-slate-500">{metric(leads.length)} leads</p><div className="my-7 flex h-4 overflow-hidden rounded-full bg-slate-100">{Object.entries(outcomes).map(([key, meta]) => <div key={key} className={meta.color} title={`${meta.label}: ${counts[key]}`} style={{ width: `${leads.length ? counts[key] / leads.length * 100 : 0}%` }} />)}</div><div className="space-y-5">{Object.entries(outcomes).map(([key, meta]) => <div key={key} className="flex items-center gap-3 text-sm"><span className={`h-2 w-2 rounded-full ${meta.color}`} /><span className="flex-1 text-slate-600">{meta.label}</span><span className="text-xs text-slate-400">{available && leads.length ? `${Math.round(counts[key] / leads.length * 100)}%` : "—"}</span><span className="w-6 text-right">{metric(counts[key])}</span></div>)}</div><div className="mt-7 border-t border-slate-100 pt-5"><p className="text-3xl">{rate(counts.booked)}</p><p className="mt-1 text-xs text-slate-500">Booking rate · completed sessions</p></div></section>
      <section className={`${card} flex items-center justify-between gap-4 lg:col-span-5`}><div><h2 className="text-base">{startedAt ? "Session time" : "Voice session"}</h2><p className="mt-4 text-4xl tracking-tight tabular-nums">{startedAt ? durationLabel(seconds) : "Ready"}</p><button onClick={onVoice} className="mt-3 min-h-11 text-xs text-violet-700 hover:underline">Open conversation ↗</button></div><div aria-hidden="true" className="relative flex h-32 w-32 shrink-0 items-center justify-center"><svg viewBox="0 0 120 120" className="absolute inset-0 h-full w-full -rotate-90"><circle cx="60" cy="60" r="49" fill="none" stroke="#eeebfb" strokeWidth="6"/><circle cx="60" cy="60" r="49" fill="none" stroke="#8B7CFF" strokeWidth="6" strokeLinecap="round" strokeDasharray="308" strokeDashoffset={startedAt ? 308 - (seconds % 60) / 60 * 308 : 90} className="transition-all duration-700"/></svg><AudioWaveform className="text-violet-400" size={32}/></div></section>
      <section className={`${card} lg:col-span-3`}><h2 className="text-base">Lead conversion</h2><p className="mt-6 text-5xl tracking-tight">{rate(counts.booked + counts.callback)}</p><p className="mt-3 text-xs leading-relaxed text-slate-500">Booked + callback<br/>of completed sessions</p><div className="mt-5 flex gap-2"><OutcomeBadge outcome="booked"/><OutcomeBadge outcome="callback"/></div></section>
      <section className={`${card} lg:col-span-5`}><h2 className="mb-4 text-base">Recent sessions</h2>{!leads.length && <p className="py-9 text-sm text-slate-500">{available ? "No sessions yet" : "Sessions unavailable"}</p>}{leads.slice(0, 3).map(lead => <div key={lead.id} className="flex items-center gap-3 border-b border-slate-100 py-3 last:border-0"><span className="w-16 shrink-0 text-[10px] text-slate-400">{dateLabel(lead.created_at)}</span><span className="min-w-0 flex-1 truncate text-xs">{prospect(lead)}</span><OutcomeBadge outcome={lead.outcome}/></div>)}</section>
      <section className="rounded-[28px] bg-[#24252B] p-6 text-white lg:col-span-4"><div className="flex items-center justify-between"><h2 className="text-base">Follow-ups</h2><ArrowUpRight size={18} className="text-white/50"/></div>{!followups.length && <p className="py-12 text-sm text-white/50">{available ? "No follow-ups" : "Follow-ups unavailable"}</p>}{followups.map(lead => <div key={lead.id} className="border-b border-white/10 py-4 last:border-0"><div className="flex items-center justify-between gap-3"><p className="truncate text-sm">{prospect(lead)}</p><span className="text-[10px] text-[#c7befa]">{outcomes[lead.outcome].label}</span></div><p className="mt-2 text-[11px] text-white/50">{dateLabel(lead.followup_time)}</p></div>)}</section>
    </div>
  </>;
}
